import test from 'node:test';import assert from 'node:assert/strict';
import {queueProspect,dispatchProspects,contactKey} from '../src/anna-runtime.js';
const lead={email:'creator@example.com',name:'Creator',observation:'Your channel features cooperative games.',channelUrl:'https://example.com/channel',contactSourceUrl:'https://example.com/contact',verifiedAt:new Date().toISOString(),publicBusinessContact:true,contactVerified:true,outreachEligible:true,language:'English',segment:'smaller growing streamers'};
function setup(){const data=new Map();const storage={async get(k){return structuredClone(data.get(k));},async put(k,v){data.set(k,structuredClone(v));},async list({prefix}){return new Map([...data].filter(([k])=>k.startsWith(prefix)));},async getAlarm(){return null;},async setAlarm(){},async transaction(fn){return fn(this);}};return {ctx:{storage,blockConcurrencyWhile:fn=>fn()},env:{ANNA_AUTO_SEND:'true',ANNA_MAIL_API_TOKEN:'test',ANNA_MAILBOX_ID:'anna'},data};}
test('Anna reserves one contact and enforces five daily sends',async()=>{const {ctx,env}=setup();for(let i=0;i<5;i++)assert.equal((await queueProspect(ctx,env,{...lead,email:`creator${i}@example.com`})).status,202);assert.equal((await queueProspect(ctx,env,lead)).status,429);assert.equal((await queueProspect(ctx,env,{...lead,email:'creator0@example.com'})).status,409);});
test('Anna suppression prevents queueing and cancels pending work',async t=>{const {ctx,env}=setup();let sends=0;const original=fetch;globalThis.fetch=async()=>{sends++;return new Response(null,{status:204});};t.after(()=>globalThis.fetch=original);await queueProspect(ctx,env,lead);await ctx.storage.put(await contactKey(lead.email),{state:'suppressed'});await dispatchProspects(ctx,env);assert.equal(sends,0);assert.equal((await queueProspect(ctx,env,lead)).status,409);});
test('Anna sends exact campaign once and never retries ambiguous outcomes',async t=>{const {ctx,env}=setup();let sends=0;const original=fetch;globalThis.fetch=async(_url,init)=>{sends++;const message=JSON.parse(init.body);assert.equal(message.displayName,'Anna | Obsidian Reign Studios');assert.match(message.text,/834-F S Perry Street #1258/);assert.match(message.text,/stop outreach/);throw Error('timeout');};t.after(()=>globalThis.fetch=original);await queueProspect(ctx,env,lead);await dispatchProspects(ctx,env);await dispatchProspects(ctx,env);assert.equal(sends,1);assert.equal((await ctx.storage.get(await contactKey(lead.email))).state,'send-outcome-unknown');});
test('Anna kill switch rejects new outreach',async()=>{const {ctx,env}=setup();env.ANNA_AUTO_SEND='false';assert.equal((await queueProspect(ctx,env,lead)).status,503);});
test('actual send-day quota prevents queued carryover exceeding five attempts',async t=>{const {ctx,env}=setup();let sends=0;const original=fetch;globalThis.fetch=async()=>{sends++;return new Response(null,{status:204});};t.after(()=>globalThis.fetch=original);await queueProspect(ctx,env,lead);const day=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Chicago',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());await ctx.storage.put('anna:attempts:'+day,5);await dispatchProspects(ctx,env);assert.equal(sends,0);assert.equal((await ctx.storage.get(await contactKey(lead.email))).state,'queued');});

