import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {JSDOM} from 'jsdom';
const source=file=>readFileSync(new URL('../'+file,import.meta.url),'utf8');
function setup(file,url){const dom=new JSDOM(source(file),{url,runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.matchMedia=()=>({matches:false,addEventListener(){}});w.HTMLElement.prototype.animate=()=>({});w.HTMLMediaElement.prototype.pause=()=>{};w.HTMLMediaElement.prototype.play=()=>Promise.resolve();w.eval(source('assets/js/studio.js'));w.eval(source('assets/js/catalog.js').replace(/export /g,'')+'\n'+source('assets/js/intake.js').replace(/^import[^\n]+\n/,''));return dom;}
const settle=()=>new Promise(r=>setImmediate(r));
test('calculator carries exact selected products into the brief and deduplicates matching add-ons',async()=>{
 const home=setup('index.html','https://obsidianreign.gg/');try{const d=home.window.document;const music=d.querySelectorAll('[data-quote]')[4];music.click();d.querySelector('[data-add-quote="199"]').click();await settle();assert.equal(d.querySelector('[data-quote-total]').textContent,'$199');const href=d.querySelector('[data-kit-link]').href;assert.match(href,/kit=music/);const brief=setup('start-project.html',href);try{const form=brief.window.document.querySelector('#project-form');assert.equal(form.elements.want_audio.checked,true);assert.match(form.elements.configuration.value,/Creator Theme Music/);assert.match(form.elements.configuration.value,/\$199/);assert.equal(brief.window.document.querySelector('[data-kit-summary]').hidden,false);}finally{brief.window.close();}}finally{home.window.close();}
});
test('project submission displays a saved reference and reuses a key on retries without sending email',async()=>{
 const dom=setup('start-project.html','https://obsidianreign.gg/start-project?reference=Arcane%20stream%20world');try{const w=dom.window,d=w.document,form=d.querySelector('#project-form');assert.match(form.elements.scope.value,/Arcane stream world/);form.elements.name.value='QA';form.elements.email.value='qa@example.test';form.elements.vibe.value='Purple';form.elements.consent.checked=true;const requests=[];w.fetch=async(url,options)=>{requests.push({url,...options});return {ok:true,json:async()=>({id:'test-reference'})};};form.dispatchEvent(new w.Event('submit',{cancelable:true}));await settle();assert.match(d.querySelector('[data-project-status]').textContent,/test-reference/);assert.match(d.querySelector('[data-project-status]').textContent,/email confirmation has not been sent/);form.dispatchEvent(new w.Event('submit',{cancelable:true}));await settle();assert.equal(requests.length,2);assert.equal(requests[0].headers['Idempotency-Key'],requests[1].headers['Idempotency-Key']);assert.equal(JSON.parse(requests[0].body).consent,true);assert.equal(d.querySelector('[data-project-email]').hidden,true);}finally{dom.window.close();}
});
test('failed submission keeps the entered brief and offers an honest email fallback',async()=>{
 const dom=setup('start-project.html','https://obsidianreign.gg/start-project');try{const w=dom.window,d=w.document,f=d.querySelector('#project-form');for(const [k,v]of Object.entries({name:'QA',email:'qa@example.test',vibe:'Purple',scope:'Test brief'}))f.elements[k].value=v;f.elements.consent.checked=true;w.fetch=async()=>{throw new Error('Network unavailable');};f.dispatchEvent(new w.Event('submit',{cancelable:true}));await settle();assert.equal(f.elements.scope.value,'Test brief');assert.equal(d.querySelector('[data-project-email]').hidden,false);assert.match(d.querySelector('[data-project-status]').textContent,/Network unavailable/);assert.equal(f.querySelector('[type=submit]').disabled,false);}finally{dom.window.close();}
});
test('navigation supports Escape and audits require privacy acknowledgement',()=>{
 const dom=setup('index.html','https://obsidianreign.gg/');try{const w=dom.window,d=w.document;const button=d.querySelector('[data-nav-toggle]');button.click();assert.equal(button.getAttribute('aria-expanded'),'true');d.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Escape',bubbles:true}));assert.equal(button.getAttribute('aria-expanded'),'false');assert.equal(d.activeElement,button);assert.equal(d.querySelector('[data-audit-form] [name=consent]').required,true);}finally{dom.window.close();}
});
