import test from 'node:test';
import assert from 'node:assert/strict';
import { ProjectHub, portal, hash, validateProject } from '../src/portal.js';

function setup(){
  const rows=new Map(); let alarm;
  const storage={get:async k=>structuredClone(rows.get(k)),put:async(k,v)=>rows.set(k,structuredClone(v)),delete:async k=>rows.delete(k),list:async({prefix})=>new Map([...rows].filter(([k])=>k.startsWith(prefix)).map(([k,v])=>[k,structuredClone(v)])),transaction:async f=>f(storage),getAlarm:async()=>alarm,setAlarm:async t=>alarm=t};
  const hub=new ProjectHub({storage}); const env={PUBLIC_ORIGIN:'https://obsidianreign.gg',PROJECT_HUB:{idFromName:x=>x,get:()=>hub}};
  const call=async(op,data={})=>(await hub.fetch(new Request('https://hub/'+op,{method:'POST',body:JSON.stringify(data)}))).json();
  const req=(path,data,cookie,origin=env.PUBLIC_ORIGIN)=>new Request(env.PUBLIC_ORIGIN+path,{method:data?'POST':'GET',headers:{...(data?{'Origin':origin,'Content-Type':'application/json'}:{}),...(cookie?{'Cookie':cookie}:{})},body:data?JSON.stringify(data):undefined});
  return {rows,env,call,req};
}
const project={title:'Private stream kit',owner:'invite:client-a',stage:0,due:'',summary:'Scope',nextStep:'Review direction',fileUrl:''};
test('private projects require login; provider configuration exposes no secrets',async()=>{const s=setup();assert.equal((await portal(s.req('/api/portal/projects'),s.env)).status,401);s.env.GOOGLE_CLIENT_ID='id';s.env.GOOGLE_CLIENT_SECRET='private';const r=await portal(s.req('/api/portal/providers'),s.env);assert.equal((await r.text()).includes('private'),false);assert.equal((await portal(s.req('/auth/client/twitch'),s.env)).headers.get('Location'),'/client-portal?notice=provider');});
test('access code is single-use, session token is hashed and only the assigned client sees records',async()=>{const s=setup();const saved=await s.call('save',project);await s.call('save',{...project,owner:'invite:other',title:'Other private project'});const code='a'.repeat(64);await s.call('invite',{id:saved.project.id,key:await hash(code)});const r=await portal(s.req('/auth/client/invite',{code}),s.env);assert.equal(r.status,200);const cookie=r.headers.get('Set-Cookie');assert.match(cookie,/Secure; HttpOnly; SameSite=Lax/);const token=cookie.split(';')[0];const sessionToken=token.split('=')[1];assert.equal(s.rows.has('session:'+sessionToken),false);assert.equal(s.rows.has('session:'+await hash(sessionToken)),true);const data=await(await portal(s.req('/api/portal/projects',null,token),s.env)).json();assert.equal(data.projects.length,1);assert.equal(data.projects[0].id,saved.project.id);assert.equal((await portal(s.req('/auth/client/invite',{code}),s.env)).status,400);await portal(s.req('/auth/client/logout',{},token),s.env);assert.equal((await portal(s.req('/api/portal/projects',null,token),s.env)).status,401);});
test('expired invites and sessions fail closed',async()=>{const s=setup();const key=await hash('a'.repeat(64));s.rows.set('invite:'+key,{user:{id:'invite:a'},expiresAt:Date.now()-1});assert.equal(await s.call('redeem',{key}),null);s.rows.set('session:'+key,{user:{id:'invite:a'},expiresAt:Date.now()-1});assert.equal(await s.call('session',{key}),null);});
test('clients cannot write feedback to another client project',async()=>{const s=setup();const p=await s.call('save',project);assert.ok((await s.call('feedback',{id:p.project.id,owner:'invite:b',message:'Intrusion'})).error);assert.equal((await s.call('all')).projects[0].timeline.length,1);assert.equal((await s.call('feedback',{id:p.project.id,owner:project.owner,message:'Please adjust the colour.'})).ok,true);});
test('cross-origin writes are rejected and brute force attempts are limited',async()=>{const s=setup();assert.equal((await portal(s.req('/auth/client/invite',{code:'a'.repeat(64)},null,'https://evil.example'),s.env)).status,403);for(let i=0;i<10;i++)assert.equal((await s.call('rate',{key:'ip'})).allowed,true);assert.equal((await s.call('rate',{key:'ip'})).allowed,false);});
test('project inputs reject script links, invalid owners and invalid milestones',()=>{assert.throws(()=>validateProject({...project,fileUrl:'javascript:alert(1)'}));assert.throws(()=>validateProject({...project,owner:'someone@example.com'}));assert.throws(()=>validateProject({...project,stage:99}));assert.equal(validateProject({...project,fileUrl:'https://drive.google.com/file/d/file/view'}).stage,0);});
test('admin project routes and direct HTML require existing admin authentication',async()=>{const s=setup();for(const path of ['/api/portal/admin/projects','/admin/projects','/project-admin','/project-admin.html'])assert.equal((await portal(s.req(path),s.env)).status,path.startsWith('/api/')?401:303);});
test('OAuth state is consumed once and PKCE verifier stays server-side',async()=>{const s=setup();s.env.KICK_CLIENT_ID='test-id';s.env.KICK_CLIENT_SECRET='secret';const r=await portal(s.req('/auth/client/kick'),s.env);const u=new URL(r.headers.get('Location'));assert.equal(u.hostname,'id.kick.com');assert.equal(u.searchParams.get('code_challenge_method'),'S256');assert.equal(u.searchParams.has('client_secret'),false);const key=await hash(u.searchParams.get('state'));const pending=await s.call('oauth-take',{key});assert.equal(pending.verifier.length,64);assert.equal(await s.call('oauth-take',{key}),null);const bad=await portal(s.req('/auth/client/kick/callback?state=wrong&code=code'),s.env);assert.equal(bad.headers.get('Location'),'/client-portal?notice=login');});
test('new invite invalidates an unused previous code for that client',async()=>{const s=setup();const p=await s.call('save',project);await s.call('invite',{id:p.project.id,key:'old'});await s.call('invite',{id:p.project.id,key:'new'});assert.equal(await s.call('redeem',{key:'old'}),null);assert.equal((await s.call('redeem',{key:'new'})).id,project.owner);});
test('agents can review and schedule follow-ups but cannot alter ownership or quotes',async()=>{const s=setup();s.env.PORTAL_AGENT_TOKEN='x'.repeat(64);const p=await s.call('save',{...project,quoteAmount:'850',quoteStatus:'Sent',internalNotes:'Studio-only notes'});assert.equal((await portal(s.req('/api/portal/agent/projects'),s.env)).status,401);const read=new Request(s.env.PUBLIC_ORIGIN+'/api/portal/agent/projects',{headers:{Authorization:'Bearer '+s.env.PORTAL_AGENT_TOKEN}});assert.equal((await(await portal(read,s.env)).json()).projects[0].internalNotes,'Studio-only notes');const schedule=new Request(s.env.PUBLIC_ORIGIN+'/api/portal/agent/followup',{method:'POST',headers:{Authorization:'Bearer '+s.env.PORTAL_AGENT_TOKEN},body:JSON.stringify({id:p.project.id,followupDate:'2026-12-10',followupNote:'Check quote response',owner:'invite:intruder',quoteAmount:'1'})});assert.equal((await portal(schedule,s.env)).status,200);const after=(await s.call('all')).projects[0];assert.equal(after.owner,project.owner);assert.equal(after.quoteAmount,'850');assert.equal(after.followupDate,'2026-12-10');assert.equal(after.activity[0].author,'Project agent');const token='client-session';await s.call('login',{key:await hash(token),user:{id:project.owner}});const client=await(await portal(s.req('/api/portal/projects',null,'__Host-or_client='+token),s.env)).json();for(const key of ['quoteAmount','quoteStatus','followupDate','followupNote','internalNotes','activity','owner'])assert.equal(key in client.projects[0],false,key);});
test('provider callbacks exchange codes server-side and create separate identity sessions',async t=>{
  const s=setup();let provider='';
  t.mock.method(globalThis,'fetch',async(url,options)=>{
    if(String(url).includes('/token')){assert.equal(new URLSearchParams(options.body).get('client_secret'),'test-secret');return new Response(JSON.stringify({access_token:'test-access'}));}
    assert.equal(options.headers.Authorization,'Bearer test-access');
    return new Response(JSON.stringify(provider==='google'?{sub:'123',name:'Google creator'}:{data:[provider==='kick'?{user_id:123,name:'Kick creator'}:{id:'123',display_name:'Twitch creator'}]}));
  });
  for(provider of ['google','twitch','kick']){
    s.env[provider.toUpperCase()+'_CLIENT_ID']='test-id';s.env[provider.toUpperCase()+'_CLIENT_SECRET']='test-secret';
    const start=await portal(s.req('/auth/client/'+provider),s.env),state=new URL(start.headers.get('Location')).searchParams.get('state');
    const r=await portal(s.req('/auth/client/'+provider+'/callback?code=valid&state='+state,null,'__Host-or_oauth='+state),s.env);
    assert.equal(r.headers.get('Location'),'/client-portal');const token=r.headers.get('Set-Cookie').split(';')[0].split('=')[1];assert.equal((await s.call('session',{key:await hash(token)})).id,provider+':123');
    const replay=await portal(s.req('/auth/client/'+provider+'/callback?code=valid&state='+state,null,'__Host-or_oauth='+state),s.env);assert.equal(replay.headers.get('Location'),'/client-portal?notice=login');
  }
});
test('preview decisions enforce ownership, latest version, one decision, and required change notes',async()=>{const s=setup();const p=(await s.call('save',{...project,reviewLabel:'Concept',reviewUrl:'https://example.com/preview-1',revisionsIncluded:'2',revisionsUsed:'0'})).project;const token='review-session';await s.call('login',{key:await hash(token),user:{id:project.owner}});const cookie='__Host-or_client='+token, route='/api/portal/review', id=p.id,versionId=p.reviews[0].id;assert.ok((await s.call('review',{id,versionId,owner:'invite:wrong',action:'approved'})).error);assert.equal((await portal(s.req(route,{id,versionId,action:'changes-requested'},cookie),s.env)).status,400);assert.equal((await portal(s.req(route,{id,versionId,action:'approved'},cookie,'https://evil.example'),s.env)).status,403);assert.equal((await portal(s.req(route,{id,versionId,action:'approved'},cookie),s.env)).status,200);assert.equal((await portal(s.req(route,{id,versionId,action:'changes-requested',message:'Overwrite'},cookie),s.env)).status,409);const updated=(await s.call('save',{...project,id,reviewLabel:'Animation',reviewUrl:'https://example.com/preview-2'})).project;assert.equal(updated.reviews[1].status,'approved');assert.equal(updated.revisionsIncluded,2);assert.equal(updated.revisionsUsed,0);assert.equal((await portal(s.req(route,{id,versionId,action:'approved'},cookie),s.env)).status,409);assert.equal((await portal(s.req(route,{id,versionId:updated.reviews[0].id,action:'changes-requested',message:'Slow down the motion'},cookie),s.env)).status,200);const final=(await s.call('all')).projects[0];assert.equal(final.reviews[0].status,'changes-requested');assert.equal(final.revisionsUsed,0);assert.equal(final.reviews[1].status,'approved');});
test('invalid preview links fail without modifying saved records and supplied history cannot overwrite decisions',async()=>{const s=setup();const p=(await s.call('save',project)).project;for(const reviewUrl of ['javascript:alert(1)','http://example.com','https://user:password@example.com'])assert.ok((await s.call('save',{...project,id:p.id,reviewLabel:'Bad',reviewUrl})).error);assert.equal((await s.call('all')).projects[0].reviews.length,0);const saved=(await s.call('save',{...project,id:p.id,reviewLabel:'Good',reviewUrl:'https://example.com/review'})).project;await s.call('review',{id:p.id,versionId:saved.reviews[0].id,owner:project.owner,action:'approved'});const after=(await s.call('save',{...project,id:p.id,reviews:[]})).project;assert.equal(after.reviews[0].status,'approved');assert.throws(()=>validateProject({...project,revisionsIncluded:'-1'}));assert.throws(()=>validateProject({...project,revisionsUsed:'1.5'}));});
