import {page,escapeHtml as e} from './public-content.js';
import {InputError} from './studio.js';
export const concepts = [
 {slug:'arcane-stream-world',title:'Arcane stream world',category:'Cinematic direction',direction:'Deep violet, arcane light and a dramatic focal point explore a fantasy-led channel identity.',media:'/assets/video/selection-fantasy.mp4',poster:'/assets/img/selection-fantasy-poster.jpg',type:'video',deliverables:'Internal motion concept. A commissioned scene family, alerts and trailer would be scoped separately.',methods:'Studio concept production; specific production tools are not documented in this showcase.',service:'/services/cinematic-streaming'},
 {slug:'subscriber-moment',title:'A subscriber moment',category:'Animated alerts',direction:'A concentrated reveal demonstrates how a support event can share the mood of the wider stream.',media:'/assets/video/event-sub.mp4',poster:'/assets/img/event-sub-poster.jpg',type:'video',deliverables:'One internal alert demonstration. Platform integration and dynamic event text are not represented by this video.',methods:'Motion concept demonstration.',service:'/services/animated-alerts'},
 {slug:'cozy-channel',title:'A place to stay',category:'Cozy scene direction',direction:'Warm lighting and softer motion explore a relaxed, welcoming channel atmosphere.',media:'/assets/video/selection-cozy.mp4',poster:'/assets/img/selection-cozy-poster.jpg',type:'video',deliverables:'Internal scene concept. No completed customer commission or performance result is claimed.',methods:'Studio concept production.',service:'/services/overlays-transitions'},
 {slug:'brand-in-motion',title:'Brand in motion',category:'Channel identity',direction:'A visual branding study exploring a cohesive presentation beyond a single static mark.',media:'/assets/video/selection-branding.mp4',poster:'/assets/img/selection-branding-poster.jpg',type:'video',deliverables:'Internal visual identity preview. Logo files and brand guidelines are not included in the preview.',methods:'Studio concept production.',service:'/services/channel-branding'}
].map(x=>({...x,origin:'Internal concept',status:'Concept demonstration',published:true}));
const clean=(value,max)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new InputError('Complete all portfolio fields within their limits.');return value.trim();};
// Publishing accepts only already-public local assets; never accepts private project links.
export function validatePortfolio(input){
 const slug=clean(input.slug,70);if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug))throw new InputError('Use a lowercase hyphenated slug.');
 if(!['video','audio','image'].includes(input.type))throw new InputError('Choose a supported media type.');
 const media=clean(input.media,300),poster=clean(input.poster,300);
 if(!/^\/assets\/(video|audio|img)\/[a-zA-Z0-9_-]+\.(mp4|webm|mp3|wav|ogg|png|jpg|jpeg|webp|gif)$/.test(media)||!/^\/assets\/img\/[a-zA-Z0-9_-]+\.(png|jpg|jpeg|webp)$/.test(poster))throw new InputError('Use an existing public asset path. Private project links are not permitted.');
 if(!['Internal concept','Client project'].includes(input.origin)||input.rightsConfirmed!==true)throw new InputError('Confirm project origin and permission to publish.');
 if(!/^\/services\/[a-z0-9-]+$/.test(input.service))throw new InputError('Use a service page path.');
 return {slug,title:clean(input.title,120),category:clean(input.category,100),direction:clean(input.direction,2000),deliverables:clean(input.deliverables,2000),methods:clean(input.methods,1000),status:clean(input.status,120),origin:input.origin,type:input.type,media,poster,service:input.service,published:input.published===true};
}
export function portfolioCards(items){return items.filter(x=>x.published).map(x=>`<article class="case-card"><a href="/work/${e(x.slug)}"><img src="${e(x.poster)}" width="960" height="540" loading="lazy" alt="${e(x.title)} preview"><div class="case-card-copy"><p class="eyebrow">${e(x.origin)} · ${e(x.category)}</p><h2>${e(x.title)}</h2><p>${e(x.direction)}</p><span class="text-link">View project details →</span></div></a></article>`).join('');}
export function portfolioPage(items){return page({title:'Work & studio concepts',description:'Explore cinematic motion, alert and branding concepts with clear scope, production status and project inquiry paths.',path:'/portfolio',body:`<section class="service-hero shell"><p class="eyebrow">THE STUDIO SHOWCASE</p><h1>See the direction.<br>Imagine your channel.</h1><p class="service-intro">Explore our motion and identity studies. Every project states whether it is internal concept work or a client commission.</p><p class="media-note">Concepts demonstrate creative direction. They are not testimonials, completed client packages or evidence of business results.</p></section><section class="section shell"><div class="case-grid">${portfolioCards(items)}</div></section><section class="section shell"><div class="cta-panel"><h2>Like a direction?</h2><p>Tell us what you would carry into your own identity.</p><a href="/start-project" class="btn btn-primary">Start a project</a></div></section>`});}
export function casePage(item){
 const media=item.type==='image'?`<a href="${e(item.media)}" target="_blank" rel="noopener"><img class="case-media" src="${e(item.media)}" alt="${e(item.title)}" width="1280" height="720"></a>`:item.type==='audio'?`<audio controls preload="none" src="${e(item.media)}" aria-label="${e(item.title)} audio preview"></audio>`:`<video class="case-media" controls playsinline preload="none" poster="${e(item.poster)}" aria-label="${e(item.title)}"><source src="${e(item.media)}"></video>`;
 return page({title:item.title,description:item.direction,path:'/work/'+item.slug,body:`<section class="service-hero shell"><a class="text-link" href="/portfolio">← All work</a><p class="eyebrow">${e(item.origin)} · ${e(item.category)}</p><h1>${e(item.title)}</h1><p class="service-intro">${e(item.direction)}</p><p class="media-note">Status: ${e(item.status)}</p></section><section class="shell">${media}<p class="media-note">${item.type==='video'?"Use the video player’s fullscreen control for a closer look.":item.type==='image'?"Open the image in a new tab to inspect it at full size.":"Use the player to listen to the audio preview."}</p></section><section class="section shell service-layout"><div><h2>What this includes</h2><p>${e(item.deliverables)}</p><h2>Production notes</h2><p>${e(item.methods)}</p></div><aside class="card service-aside"><p class="eyebrow">YOUR NEXT STEP</p><h2>Build your own direction.</h2><p>Reference this project in your brief. Your scope, formats and licensing are confirmed before production.</p><a class="btn btn-primary" href="/start-project?reference=${encodeURIComponent(item.title)}">Discuss a similar direction</a><a class="text-link" href="${e(item.service)}">Explore the service →</a></aside></section>`});
}
